### ISSUE TITLE
SCLM Migration having issues - dbb/Migration/sclm 

### ISSUE THREAD

**Issue by riyazkha** [IBM/dbb#105]
extrmetadata.sh
Executes EXTARCH
Creates data set 'F03923F.SCLMMIG.REXX'
Copies file /u/f03923f/DBB/Migration/sclm/groovy/../rexx/EXTARCH.rexx to F03923F.SCLMMIG.REXX(EXTARCH)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/SORTDB.rexx macro to F03923F.SCLMMIG.REXX(SORTDB)
Caught: java.lang.UnsatisfiedLinkError: DBB_JNI (Not found in java.library.path)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/SORTVER.rexx macro to F03923F.SCLMMIG.REXX(SORTVER)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERRETR.rexx macro to F03923F.SCLMMIG.REXX(VERRETR)
java.lang.UnsatisfiedLinkError: DBB_JNI (Not found in java.library.path)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../conf/sclmmig.config to F03923F.SCLMMIG.REXX(MIGCFG)
	at com.ibm.dbb.build.internal.jni.Executable.loadNativeLibrary(Executable.java:37)
	at com.ibm.dbb.build.internal.jni.Executable.<clinit>(Executable.java:29)
Creates data set 'F03923F.SCLMMIG.SKELS'
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERJOBC.skel macro to F03923F.SCLMMIG.SKELS(VERJOBC)
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.getProductStatus(ProductRegistrationChecker.java:197)
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.check(ProductRegistrationChecker.java:103)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERRETR.skel macro to F03923F.SCLMMIG.SKELS(VERRETR)
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.check(ProductRegistrationChecker.java:67)
	at com.ibm.dbb.build.AbstractExec.execute(AbstractExec.java:63)
Executes F03923F.SCLMMIG.REXX(EXTARCH)
/u/f03923f/DBB/Migration/sclm/bin>
	at com.ibm.dbb.build.IExecute$execute.call(Unknown Source)
	at SclmExtract.run(SclmExtract.groovy:196)
** Build finished
/u/f03923f/DBB/Migration/sclm/bin>
Executes EXTMEMB
Creates data set 'F03923F.SCLMMIG.REXX'
Caught: java.lang.UnsatisfiedLinkError: DBB_JNI (Not found in java.library.path)
Copies file /u/f03923f/DBB/Migration/sclm/groovy/../rexx/EXTMEMB.rexx to F03923F.SCLMMIG.REXX(EXTMEMB)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/SORTDB.rexx macro to F03923F.SCLMMIG.REXX(SORTDB)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/SORTVER.rexx macro to F03923F.SCLMMIG.REXX(SORTVER)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERRETR.rexx macro to F03923F.SCLMMIG.REXX(VERRETR)
java.lang.UnsatisfiedLinkError: DBB_JNI (Not found in java.library.path)
	at com.ibm.dbb.build.internal.jni.Executable.loadNativeLibrary(Executable.java:37)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../conf/sclmmig.config to F03923F.SCLMMIG.REXX(MIGCFG)
	at com.ibm.dbb.build.internal.jni.Executable.<clinit>(Executable.java:29)
Creates data set 'F03923F.SCLMMIG.SKELS'
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.getProductStatus(ProductRegistrationChecker.java:197)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERJOBC.skel macro to F03923F.SCLMMIG.SKELS(VERJOBC)
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.check(ProductRegistrationChecker.java:103)
	at com.ibm.dbb.build.internal.ProductRegistrationChecker.check(ProductRegistrationChecker.java:67)
	at com.ibm.dbb.build.AbstractExec.execute(AbstractExec.java:63)
	at com.ibm.dbb.build.IExecute$execute.call(Unknown Source)
Copies /u/f03923f/DBB/Migration/sclm/groovy/../rexx/VERRETR.skel macro to F03923F.SCLMMIG.SKELS(VERRETR)
	at SclmExtract.run(SclmExtract.groovy:196)
Executes F03923F.SCLMMIG.REXX(EXTMEMB)
/u/f03923f/DBB/Migration/sclm/bin>
** Build finished

**Comment by riyazkha** [comment]
java 8 64 bit solved above issue
