### ISSUE TITLE
CobolCompile.groovy failing

### ISSUE THREAD

**Issue by ianc-d** [IBM/dbb#14]
Starting off with Groovy and DBB. 
Using the samples provided, DBB and z Open Development...

Running DBB Build on the PrintApp.cbl file, we get messages saying the DBB User Build is complete for PRINTAPP.CBL. Looking at more details in the log we see...

RSEG1106: File .../work/PRINTAPP.log not found on host....

Together with the resultant java exception

** Build start at 20190912.012102.021
/u/home/.../DBB_Sandbox>
Caught: com.ibm.jzos.ErrnoException: EDC5129I No such file or directory. ERRNO=129 ERRNO2=0x594003d
com.ibm.jzos.ErrnoException: EDC5129I No such file or directory. ERRNO=129 ERRNO2=0x594003d
	at com.ibm.jzos.FileAttribute.stat(Native Method)
	at com.ibm.jzos.FileAttribute.getStat(FileAttribute.java:595)
	at com.ibm.dbb.build.internal.Utils.retrieveHFSEncoding(Utils.java:119)
	at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:120)
	at com.ibm.dbb.build.BuildProperties$load$0.call(Unknown Source)
	at Tools.loadProperties(Tools.groovy:107)
	at Tools$loadProperties.call(Unknown Source)
	at build.run(build.groovy:63)

Looking at the z/OS file system, all assets (.cbl, properties files and groovy scripts) are there and look fine. It is true that the .log file hasn't been created yet and thus the exception.

Online documentation states that one should "add the project folder to the file.properties file" (https://www.ibm.com/support/knowledgecenter/en/SSUFAU_1.0.0/com.ibm.idz.dbbz.doc/topics/DBBz_troubleshooting.html).

Is the sample missing this information? I couldn't fine any direction as to what to put into the file.properties file.

**Comment by ianc-d** [comment]
Closing.
