### ISSUE TITLE
JCLExec() call issuing null pointer exception

### ISSUE THREAD

**Issue by ChristopherJohns-GMCom** [IBM/dbb#163]
Hello,

I'm using the JCLExec() function with dynamically built in-stream JCL.  When the function is called, the script fails with a java.lang.NullPointerException error  after submitting job 'null'.  I'm following the example in the IBM manual.

This is the error block with a few previous DEBUG and println() messages:

2023-05-03T16:37:57.9180846Z test parsing the source file </u/***/DBBworkspace/ChriJohn/MF_CHRIS_TESTING/CHRIS/jcl/k13rpbs1.jcl>.
2023-05-03T16:37:57.9181167Z 
2023-05-03T16:37:57.9191217Z The second to last should be the folder, I hope.. jcl.
2023-05-03T16:37:57.9191490Z 
2023-05-03T16:37:57.9192147Z JCL Check will run on P-Plex.
2023-05-03T16:37:57.9192300Z 
2023-05-03T16:37:57.9196691Z The generated job is:
2023-05-03T16:37:57.9197281Z <      //NZD3SLA  JOB (BLEPP5),'CHRIS JOHNS ',
2023-05-03T16:37:57.9197881Z       //            CLASS=N,MSGCLASS=A,NOTIFY=&SYSUID
2023-05-03T16:37:57.9198689Z       //NADA     EXEC PGM=IEFBR14
2023-05-03T16:37:57.9199156Z       //SYSPRINT DD SYSOUT=*
2023-05-03T16:37:57.9199591Z       //HCIXML   DD  DISP=SHR,
2023-05-03T16:37:57.9200022Z       //         DSN=NZD3SL.BIDTEST.ASM      
2023-05-03T16:37:57.9200517Z       >.
2023-05-03T16:37:57.9200690Z 
2023-05-03T16:37:57.9241432Z DEBUG	2023-05-03T16:37:57,919	43498	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	Checking product registration
2023-05-03T16:37:57.9241848Z 
2023-05-03T16:37:57.9242874Z DEBUG	2023-05-03T16:37:57,919	43498	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	Checking product status for : {"productId":"5655-AC6","featureName":"DBB","productName":"IBM APP DLIV FND"}
2023-05-03T16:37:57.9243374Z 
2023-05-03T16:37:57.9249531Z DEBUG	2023-05-03T16:37:57,920	43499	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	result = [B@6392d1c returnCode = 0 flag = 32
2023-05-03T16:37:57.9250089Z 
2023-05-03T16:37:57.9251076Z DEBUG	2023-05-03T16:37:57,920	43499	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	Product Registration: Start registering the product id, 5655-AC6
2023-05-03T16:37:57.9251504Z 
2023-05-03T16:37:57.9252482Z DEBUG	2023-05-03T16:37:57,920	43499	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	Product registration was completed with NAME=IBM APP DLIV FND FEATURE=DBB VERSION=*.*.* ID=5655-AC6
2023-05-03T16:37:57.9252951Z 
2023-05-03T16:37:57.9253983Z DEBUG	2023-05-03T16:37:57,920	43499	com.ibm.dbb.build.internal.ProductRegistrationChecker	[main]	Registered for product = {"productId":"5655-AC6","featureName":"DBB","productName":"IBM APP DLIV FND"}
2023-05-03T16:37:57.9254452Z 
2023-05-03T16:37:57.9255364Z DEBUG	2023-05-03T16:37:57,921	43500	com.ibm.dbb.build.JCLExec	[main]	Enable Security Trace: false
2023-05-03T16:37:57.9256021Z 
2023-05-03T16:37:57.9300422Z DEBUG	2023-05-03T16:37:57,925	43504	com.ibm.dbb.build.JCLExec	[main]	Submitting job 'null' at May 3, 2023 4:37:57 PM
2023-05-03T16:37:57.9300796Z 
2023-05-03T16:37:59.0206883Z ##[error]Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at com.ibm.dbb.build.internal.jcl.JclSubmitStatusRetriever.getJobStatusRexxCommand(JclSubmitStatusRetriever.java:141)
	at com.ibm.dbb.build.internal.jcl.JclSubmitStatusRetriever.getStatus(JclSubmitStatusRetriever.java:59)
	at com.ibm.dbb.build.JCLExec.doExecute(JCLExec.java:171)
	at com.ibm.dbb.build.JCLExec.execute(JCLExec.java:120)
	at nonBuild$_run_closure2.doCall(nonBuild.groovy:128)
	at nonBuild.run(nonBuild.groovy:50)
	at nonBuild$run.callCurrent(Unknown Source)
	at BMS$run.callCurrent(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader._run(ScriptLoader.groovy:124)
	at com.ibm.dbb.groovy.ScriptLoader$_run$0.call(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader$_run$0.call(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader.runScript(ScriptLoader.groovy:81)
	at build$_run_closure1.doCall(build.groovy:49)
	at build.run(build.groovy:46)

This is the portion of the script that executes the call:

   println "test parsing the source file <$srcFile>."
   String[] str
   str = srcFile.split('/')
   println "The second to last should be the folder, I hope.. " + str[-2] + "."   
   if (str[-2] == 'jcl') {
      println "JCL Check will run on P-Plex."
      def confDir = "/usr/lpp/ibm/dbb/current/conf"
      def jcl = '''\
      //NZD3SLA  JOB (BLEPP5),'CHRIS JOHNS ',
      //            CLASS=N,MSGCLASS=A,NOTIFY=&SYSUID
      //NADA     EXEC PGM=IEFBR14
      //SYSPRINT DD SYSOUT=*
      //HCIXML   DD  DISP=SHR,
      //         DSN=NZD3SL.BIDTEST.ASM      
      '''
      println "The generated job is:"
      println "<$jcl>."
      
      new JCLExec().text(jcl).confDir(confDir).execute()

What am I doing wrong?

Thanks,

Chris

**Comment by ChristopherJohns-GMCom** [comment]
Hi Dennis,
The job never submits.  The pipeline stops running at the error.

Here is the Version info from /bin/version.properties

version=1.1.3
build=151
date=28-Feb-2022 17:26:26   

Thanks,

Chris

**Comment by M-DLB** [comment]
Hello @ChristopherJohns-GMCom - I can't reproduce the problem with our DBB 1.1.3 installation.
Can this JCL be submitted manually to JES with no problem with your user?
Could it be blocked by any security or configuration parameters by JES on your site?

**Comment by ChristopherJohns-GMCom** [comment]
Hello @M-DLB 

Thanks for the feedback.  The example JCL runs without error or issue when submitted to JES.

I did locate an error in configuration in file /conf/dbbenv.sh.  The export DBB_HOME and export DBB_CONF path specifications were incorrect.  I'm having them corrected, I'll re-test and let you know if that was the cause of the error.

**Comment by ChristopherJohns-GMCom** [comment]
Hello @M-DLB 

The /conf/dbbenv.sh configuration has been corrected, but I'm still getting the 'null' error.

Chris

**Comment by ChristopherJohns-GMCom** [comment]
Another item I found.

it seems that there is an error trying to locate the REXX script named jobStatus.  

##[error]Caught: java.lang.NullPointerException

##[error]java.lang.NullPointerException
	at com.ibm.dbb.build.internal.jcl.JclSubmitStatusRetriever.getJobStatusRexxCommand(JclSubmitStatusRetriever.java:141)
	at com.ibm.dbb.build.internal.jcl.JclSubmitStatusRetriever.getStatus(JclSubmitStatusRetriever.java:59)
	at com.ibm.dbb.build.JCLExec.doExecute(JCLExec.java:171)
	at com.ibm.dbb.build.JCLExec.execute(JCLExec.java:120)

These are the import statements in the script:

import com.ibm.dbb.repository.*
import com.ibm.dbb.dependency.*
import com.ibm.dbb.build.*
import com.ibm.dbb.build.DBBConstants.CopyMode
import com.ibm.dbb.build.report.*
import com.ibm.dbb.build.html.*
import com.ibm.dbb.build.JCLExec.*
import com.ibm.dbb.build.internal.jcl.JclSubmitStatusRetriever.*
import com.ibm.dbb.build.internal.jcl.*
import groovy.util.*
import groovy.transform.*
import groovy.time.*
import groovy.xml.*
import groovy.cli.commons.*
import groovy.ant.*

Am I missing one?

**Comment by M-DLB** [comment]
Hello @ChristopherJohns-GMCom - The path to the jobStatus REXX script is calculated based on the configDir variable, which should point to your configuration folder. The absolute path of the jobStatus script is `configDir/jobStatus`.
If set to an empty string when calling JCLExec, the configDir is determined from the DBB_CONF environment variable. If this variable is not SET, it is determined from the DBB_HOME variable, adding `/conf`.
I think you should verify that the configDir you pass in the JCLExec is pointing to the right location, or potentially remove it and let DBB use the DBB_CONF environment variable.
Please let us know if you pass this hurdle.

**Comment by ChristopherJohns-GMCom** [comment]
Hello @M-DLB ,

I located the jobStatus REXX program.  It is in the default location you mentioned above.  The dbbenv.sh member has been updated to reflect the correct values for DBB_HOME and DBB_CONF.

I ran the pipeline both with and without specifying configDir.  The runs produced the same errors as listed above both times.

I do not know how to proceed from here.

Chris

**Comment by M-DLB** [comment]
Hello @ChristopherJohns-GMCom ,

You mentioned it's running in a pipeline. Are these environment variables correctly populated in the pipeline's agent environment? Does the pipeline's agent has read+execute access to the `configDir` directory?
Does the script work when you run it with your userID ?

Sorry for these dumb questions, just trying to narrow down the problem!

**Comment by ChristopherJohns-GMCom** [comment]
Hello @M-DLB,

The script runs successfully before I made these changes to run a dynamic JCL job.  It runs successfully if I build a JCL job using the MVSJob() method.

The problem only happens when I use dynamically built JCL.  I have to use this because the use of MVSJob() or JCLExec() depends on where the JCL has to run.  MVSJob() is for local execution, which works fine.  JCLExec() is for remote execution since I have to specify /*ROUTE XEQ in the Jobcard for the remote submission.

All of our existing pipelines/scripts have been running without issue for the 2 years since we converted.  The needed access was granted back then to our agents and IDs.

Chris

**Comment by ChristopherJohns-GMCom** [comment]
Hi @M-DLB,

I understand completely.  I'll open an ETR with IBM support.

If I close this issue, will I still be able to update it with a resolution in case someone else has this same problem?
If not, can it be left open or is there a time limit when inactive issues will be automatically closed?

Thanks again,

Chris

**Comment by M-DLB** [comment]
Hi @ChristopherJohns-GMCom ,

I think it can be closed safely, it will be accessible in the list of closed issues.
If you feel it would be better to keep it open until a resolution is found, it's still OK, if you want to update it when the problem is fixed.
