### ISSUE TITLE
DBB Integrating with Jenkins Not Working - ERROR: Error cloning remote repo 'origin'

### ISSUE THREAD

**Issue by ptamil1989** [IBM/dbb#27]
Hi All,
For the first time i am integrating DBB with Jenkins and i am getting 'ERROR: Error cloning remote repo 'origin'' error. Not sure where exactly the issue resides, i have followed IBM DBB jenkins configuration mentioned in IBM portal but it is not working for me. Can any one help me to find out the issue?

Cloning the remote Git repository
Cloning repository D:\Udhay\MortgageApplication
 > /Z23D/usr/lpp/IBM/dbb/bin/git-jenkins.sh init /DevOps/jenkins/workspace/Mortgage Application # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /DevOps/jenkins/workspace/Mortgage Application
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:989)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:747)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:812)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to IBM DBB Node
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor1455.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy88.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1114)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1159)
		at hudson.scm.SCM.checkout(SCM.java:505)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1205)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1853)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:427)
Caused by: hudson.plugins.git.GitException: Command "/Z23D/usr/lpp/IBM/dbb/bin/git-jenkins.sh init /DevOps/jenkins/workspace/Mortgage Application" returned status code 127:
stdout: test: /Z23D/usr/lpp/IBM/dbb/bin/git-jenkins.sh 10: not found
git: /Z23D/usr/lpp/IBM/dbb/bin/git-jenkins.sh 29: not found
iconv: /Z23D/usr/lpp/IBM/dbb/bin/git-jenkins.sh 29: not found

stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2429)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2359)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2355)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1915)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:987)
	... 11 more
ERROR: Error cloning remote repo 'origin'
Finished: FAILURE

**Comment by dennis-behm** [comment]
Hi ptamil1989, are you able to clone from the cmdline? What is the user of the Jenkins agent? Have you thought about the ssh_keys?

**Comment by ptamil1989** [comment]
Hi Dennis,
Even with command line i am not able to clone. My Jenkins agent user is 'ibmuser' (Default USS login)', not sure how to clone with ssh keys.

**Comment by dennis-behm** [comment]
ptamil1989, a bunch of additional questions to understand your setup: What is your selected git provider? Can you ping the git server from the mainframe (just use tso.6 and try a ping)? Which version of Rocket Git have you installed in your mainframe environment? When you write about the 'ibmuser', is this an ZD&T environment?

**Comment by dennis-behm** [comment]
@ptamil1989 is this issue being resolved? I have not seen a update for quite some weeks. Thanks, Dennis

**Comment by dennis-behm** [comment]
Closing the issue due to inactivity.
