### ISSUE TITLE
LinkEdit Groovy Script failing

### ISSUE THREAD

**Issue by Shalini174** [IBM/dbb#9]
Hi, my LinkEdit Groovy script is failing for below line. I am not sure what is the purpose of the line.Please help:

tools.updateBuildResult(file:"$file", rc:rc, maxRC:0, log:logFile)

i am getting java null exception error for this line.

**Comment by drbruce-git** [comment]
@Shalini174 can you copy the console output with the null pointer exception message so that I can see it?

**Comment by Shalini174** [comment]
Hi Bruce, below is the exception message:

/rsusr/HelloWorld>
Link editing link file hello.cbl
/rsusr/HelloWorld>
Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at com.ibm.dbb.repository.RepositoryClient.getRestAPIUrl(RepositoryClient.java:664)
	at com.ibm.dbb.repository.RepositoryClient.getBuildResult(RepositoryClient.java:891)
	at com.ibm.dbb.repository.RepositoryClient$getBuildResult$2.call(Unknown Source)
	at Tools.getBuildResult(Tools.groovy:197)
	at Tools.updateBuildResult(Tools.groovy:256)

**Comment by Shalini174** [comment]
Bruce, 
Also when i tried to use the LinkEdit.groovy for my HelloWorld program, i was getting value for "file" as : 
"--SourceDir" on the following line execution: 

def file = args[0]

Do i need to modify any file for the LinkEdit script to work? I am new to Groovy, please suggest.

**Comment by drbruce-git** [comment]
@Shalini174 the null pointer exception is occurring when the Groovy script is trying to connect to the DBB web application to update the build result.  I think the problem is that you are trying to invoke LinkEdit.groovy directly but it is designed to be called from the MortgageApplication's build.groovy.  All of the parameters like --sourceDir and such are expected by build.groovy and loaded into a static properties class.  Then build.groovy calls LinkEdit.groovy only passing the name of the link card to link.

If you are just trying to LinkEdit hello.cbl, I think you would be better off editing hello_cbl.groovy and adding a link-edit step  See MortgageApplication/build/CobolCompile.groovy for an example of a script that compiles and link-edits a source file in one script.

**Comment by drbruce-git** [comment]
One of our new developers has posted a Linked-in article at https://www.linkedin.com/pulse/modern-development-zos-kaleb-porter/ showing how to compile, link and execute a simple program using Groovy and DBB.

**Comment by Shalini174** [comment]
@drbruce-git : LinkEdit is working fine if i comment the build report  step. But i below query:
I am trying to install DBB server(trial version) on my system, but when i try to unzip the file "dbb-server-1.0.3.tar.gz" i am getting error : FSUM7449 ././@LongLink: Unknown file type field value 'L'.

Even after this error i can see the wlp,server directories but when i try to edit the dbb.properties file, i see special  characters. 
Please suggest.

**Comment by drbruce-git** [comment]
@Shalini174 is this still an issue?

**Comment by dennis-behm** [comment]
Closing due to inactivity
